INSERT INTO NhanVienKiemKho VALUES (11);
INSERT INTO NhanVienKiemKho VALUES (12);
INSERT INTO NhanVienKiemKho VALUES (13);
INSERT INTO NhanVienKiemKho VALUES (14);
INSERT INTO NhanVienKiemKho VALUES (15);
INSERT INTO NhanVienKiemKho VALUES (16);
INSERT INTO NhanVienKiemKho VALUES (17);
INSERT INTO NhanVienKiemKho VALUES (18);
INSERT INTO NhanVienKiemKho VALUES (19);
INSERT INTO NhanVienKiemKho VALUES (20);
INSERT INTO NhanVienKiemKho VALUES (21);
INSERT INTO NhanVienKiemKho VALUES (22);
INSERT INTO NhanVienKiemKho VALUES (23);
INSERT INTO NhanVienKiemKho VALUES (24);
INSERT INTO NhanVienKiemKho VALUES (25);

